# Generated by Django 5.0 on 2024-01-09 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoVenta',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NUMERO_FACTURA', models.CharField(editable=False, max_length=20, null=True)),
                ('FECHA_EMISION', models.DateField(editable=False, null=True)),
                ('MONEDA', models.CharField(editable=False, max_length=60, null=True)),
                ('MONTO', models.DecimalField(decimal_places=2, editable=False, max_digits=18, null=True)),
                ('TIPO_CLIENTE', models.CharField(editable=False, max_length=60, null=True)),
                ('NOMBRE_CLIENTE', models.CharField(editable=False, max_length=150, null=True)),
                ('CONDICION_PAGO', models.CharField(editable=False, max_length=60, null=True)),
                ('VENDEDOR', models.CharField(editable=False, max_length=60, null=True)),
                ('CANCELADO', models.CharField(editable=False, max_length=1, null=True)),
                ('ESTADO', models.CharField(editable=False, max_length=3, null=True)),
                ('ESTATUS', models.CharField(default='Emitido', max_length=20)),
                ('FECHA_ENTREGA', models.DateField(null=True)),
                ('COMENTARIOS', models.CharField(max_length=400, null=True)),
                ('DATOS_ADJUNTOS', models.FileField(blank=True, null=True, upload_to='adjuntos/')),
                ('PERSONAL_ASIGNADO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.personal')),
            ],
        ),
    ]
